name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    if: always() # Menjalankan walaupun sebelumnya gagal
    steps:
      - name: Re-run Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/rayanpip/life/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
